export enum FilterMatchType {
  EXACT = 'EXACT',
  MATCH_TYPE_UNSPECIFIED = 'MATCH_TYPE_UNSPECIFIED',
  BEGINS_WITH = 'BEGINS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  CONTAINS = 'CONTAINS',
  FULL_REGEXP = 'FULL_REGEXP',
  PARTIAL_REGEXP = 'PARTIAL_REGEXP',
}
